### ISSUE TITLE
Convert cart to text message

### ISSUE THREAD

**Issue by mgCool2** [mgCool2/mgCool2.github.io#3]
- [x] Take the content of the cart and convert it into url encoded text

**Comment by mgCool2** [comment]
See https://www.w3schools.com/jsref/jsref_encodeuri.asp for converting 

https://wa.me/91XXXXXXXXXX?text=I'm%20interested%20in%20your%20car%20for%20sale

**Comment by mgarg1** [comment]
https://wa.me/919000141295?text=I'm%20interested%20in%20your%20car%20for%20sale
